### ISSUE TITLE
Low Updating rate comparing to original single radar ros reciever program by TI

### ISSUE THREAD

**Issue by SladeLu** [oyrl/xWR1xxx_sid#1]
Thanks a lot!
It almost kill me to write a multi-radar receiver program. Luckily find your open source codes!

However, when i applied them correctly on two TI IWR1443 radar, no mistakes happened but get a very low Point cloud updating rate comparing to original single radar ros TI demo program.  

In your program, the point cloud updates about 1 frame per second. The TI demo updates about 10-20 frames per second.  Do you find out this problem or just my mistakes and how to fix this. Just some clues are enough!

Thanks again!

**Comment by SladeLu** [comment]
Even if only setting one radar, the update rate maintains in 2-3 frame per second.

**Comment by SladeLu** [comment]
Problem solved! I delete the doppler velocity calculation  in "DataHandlerClass.cpp" and the FPS rising to the normal level. Thanks again.

**Comment by oyrl** [comment]
Sorry, I don't have the low updating rate issue. In my experiment, the update rate was about 30 Hz, which means that the frame period is about 33 ms. Do you connect other devices to the same USB controller, such as a camera?
